// ruvolan/st.n
#pragma once
#include "st/Примитив.hpp"
#include "st/Слово.hpp"
#include "st/Глагол.hpp"
#include "st/Предлог.hpp"
#include "st/Прилагательное.hpp"
#include "st/Существительное.hpp"
#include "st/Форма.hpp"
